webinterface/urls.py
from django.conf.urls import url
from . import views

app_name = 'webinterface'

urlpatterns = [
    # host/
    url(r'^$', views.index, name='index'),
    # host/goal/glance/
    url(r'^goal/glance/$', views.goal_glance, name='goal_glance'),
]

webinterface/views.py
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie


def index(request):
    return render(request, 'webinterface/index/index.html')


@ensure_csrf_cookie
def goal_glance(request):
    return render(request, 'webinterface/goal/glance.html')

webinterface/templates/webinterface/home/home.html
{% extends 'webinterface/base.html' %}
{% block extra_headers %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min.js"></script>
{% endblock %}
{% block title %}\Errands{% endblock %}
{% block body %}
    <div class="row" style="position: relative;top: 25vh;">
        <div class="col l0 m0 s0"></div>
        <div class="col l12 m12 s12 center align">
            <div class="card-content">
                <h1>Escape</h1>
                <div class="flow-text grey-text">(Your)</div>
                <h1>Errands</h1>
            </div>
            <ul>
                <li><a href="{% url 'webinterface:goal_glance' %}">Have a glance on your goals</a></li>
            </ul>
        </div>
        <div class="col l0 m0 s0"></div>
    </div>
{% endblock %}

webinterface/templates/webinterface/index/index.html
{% extends 'webinterface/base.html' %}
{% block extra_headers %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min.js"></script>
{% endblock %}
{% block title %}\Errands{% endblock %}
{% block body %}
    <div class="row" style="position: relative;top: 25vh;">
        <div class="col l0 m0 s0"></div>
        <div class="col l12 m12 s12 center align">
            <div class="card-content">
                <h1>Escape</h1>
                <div class="flow-text grey-text">(Your)</div>
                <h1>Errands</h1>
            </div>
            <ul>
                <li><a href="{% url 'webinterface:goal_glance' %}">Have a glance on your goals</a></li>
            </ul>
        </div>
        <div class="col l0 m0 s0"></div>
    </div>
{% endblock %}